### ISSUE TITLE
Need improved auto-optimized force field support

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#143]
A decision is needed on whether to include RDKit or add a command-line server for Open Babel's force field code.

- RDKit offers MMFF94 and UFF and distance geometry conformer searching
- Open Babel offers MMFF, UFF and GAFF, plus several different conformer options

**Comment by cryos** [comment]
From previous email discussions I would love to explore deeper integration with RDKit. I don't think it has to be exclusive of any further integration of Open Babel ( I think linking to Open Babel is a dead end due to GPLv2 only).

There are some great features in RDKit, and I would like to get more familiar with it/better understand how we might use it. Whenever I try to figure out how to do things in C++ I seem to get stuck, is this because I should just use the Python API or is it just a learning curve issue? I couldn't find any examples of using the C++ API to help get started.

**Comment by ghutchis** [comment]
I'd ask Greg Landrum. I think he expects most people to use the Python API, so there aren't many C++ examples.

**Comment by ghutchis** [comment]
The new force field framework in #1370 handles this - you can easily write Python scripts to get energies and gradients from anything.
