### ISSUE TITLE
Downloading dependencies for avogadrolibs

### ISSUE THREAD

**Issue by etp12** [OpenChemistry/avogadrolibs#172]
I'm working on setting up a continuous integration environment for avogadrolibs through [Appveyor](https://www.appveyor.com/). This would be able to automatically build branches and pull requests to confirm that they build before merging them. In order for these branches and PRs to be detected and built automatically, I need to select a Github repository in the Appveyor UI. The problem with this that I've encountered so far is that a lot of dependencies required for building avogadrolibs are downloaded in the scripts inside the openchemistry repository. 

Would it be possible to add or move the scripts used to download dependencies into this repository to allow for the use of a continuous integration service?

**Comment by cryos** [comment]
No, the whole point of the superbuild is to remove all of the cruft of dependencies from the actual repository. We have used AppVeyor for another project, and we were able to keep the separation of superbuild and project repository. Isn't it possible to select this as the repository, download the superbuild, and just change the target to build the relevant dependencies only? For example, you can try this locally, but configure the openchemistry repository and then call

    cmake --build . --target eigen --config Release

We could probably look at adding a dummy target to the openchemistry repository, something like build all dependencies, so that it will build dependencies but not avogadrolibs. I don't know what approach you have tried, but I think there are solutions with AppVeyor, CircleCI, and other free GitHub CIs. We have had to prebuild some of the larger dependencies for AppVeyor and CircleCI in other projects, avogadrolibs may be OK in this case.

**Comment by etp12** [comment]
I've been able to make progress by manually cloning the superbuild and then cloning the specific avogadrolibs commit to be built. Then I can target avogadrolibs specifically.

Thanks for the reply! I'll close this issue with this comment.

**Comment by cryos** [comment]
Sounds good, glad you were able to take an alternate approach.
