### ISSUE TITLE
Export to SVG

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#290]
Open Babel supports an SVG "ball and stick" rendering style, which works well for 2D depiction of molecules.

https://pqr.pitt.edu/static/data/svg/IE/IEDVJHCEMCRBQM-UHFFFAOYSA-N.svg
<img width="330" alt="screen shot 2018-07-04 at 5 36 29 pm" src="https://user-images.githubusercontent.com/41128/42294674-d68664ec-7fb0-11e8-8afb-4965a5f9ffbe.png">

For Avogadro, we can directly map to 2D using the camera.

One tricky thing would be working out z-depth mapping (i.e., write out the back atoms first) and scaling the radii of the atoms, but that shouldn't be too hard.

**Comment by serk12** [comment]
Hi I've done a first template [here](https://github.com/serk12/avogadrolibs/). But I'm missing something, how the glwidget does the culling. I think this is because the `m_camera->width()` and  `m_camera->height()` returns the pixel size but not the projection position? For the moment this is with a magic number. Any idea?

**Comment by ghutchis** [comment]
I know that @cryos did that part of the code, so I'm tagging him. I think for a first PR, I'd be okay without culling.
