### ISSUE TITLE
Port spectra extension from Avo1

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#309]
The Spectra plot extension should be ported from Avo1 to use the new VTK plots.

- [x] Offer Gaussian or Lorentzian broadening
- [ ] Allow overlay of experimental (or other) spectra
- [ ] Save graphics
- [ ] Save plot data as CSV or TSV
- [x] Plot IR spectra (as transmission or absorbance)
- [x] Plot Raman spectra
- [x] Plot electronic excitations as UV/Vis spectra
- [x] Plot CD spectra
- [ ] Plot NMR

**Comment by ghutchis** [comment]
Some of these features (graphics, saving plot data) could become general features of the `vtkplot.cpp` code.

**Comment by drew-parsons** [comment]
@ghutchis  A big yes-please for this feature.  The vibration animation works fine in current avogadro (reading NWChem frequency output). Would be a boon if avogadro could plot (and save) the corresponding IR spectrum.

Point 4 would be useful also (an option to print the line-broadened plotting data to text file), in order to enable fine control of the formatting of the plot using other plotting tools.

**Comment by ghutchis** [comment]
@drew-parsons - it's definitely on my summer agenda this year. In the meantime, I think there are some nice options via `cclib`. If they don't have an example script, bug me and I'll post one.

**Comment by ghutchis** [comment]
Okay, both `avogadro-cclib` and Open Babel should now write vibrations, IR/Raman, electronic and NMR spectra data to `cjson` format.

I think I'm also going to change file handling in avogadrolibs to try `cclib` if available and then Open Babel .. should provide a better experience for  most people.

**Comment by ghutchis** [comment]
The remaining work involves:
- [ ] reading / writing spectra in Avogadro's `cjsonformat` code
- [ ] storing spectra in the `Molecule` class .. probably as properties.
- [ ] adding some initial spectral drawing code

**Comment by ghutchis** [comment]
Most of this is integrated into #1429
