### ISSUE TITLE
Undo/Redo needs "checkpoints"

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#63]
I think the automatic undo/redo needs a method to declare a "checkpoint."

Right now, the draw tool will create a ton of "move atom" undos - instead, the user probably wants an "undo all of that"

I think the best technique would be something like:
http://doc.qt.io/qt-5/qundostack.html#beginMacro
http://doc.qt.io/qt-5/qundostack.html#endMacro

In all likelihood, mergeWith() also needs to be used more to cut down on the size of the undo stack.

**Comment by psavery** [comment]
I wholeheartedly agree with this. If I left click to create a carbon atom with "Adjust Hydrogens" checked, it takes 14 undo calls to undo that single left click:

1 undo for each bond (4 of them)
1 undo for each hydrogen creation (4 of them)
1 undo for each hydrogen translation (4 of them)
1 undo for carbon translation
1 undo for carbon creation

When dragging in the draw tool, I have experienced a lot more "slowness" on slower computers than I did in Avogadro 1, and I think the undo stack is a big contributor to that because it gets updated multiple times for a single, smooth drag. The undo stack should probably only get updated when the mouse is released like it does in Avogadro 1.

**Comment by ghutchis** [comment]
@cryos I think there are two key problems:

- interactiveMode still creates intermediate undo items (better to just do the final one)
- interactiveMode undo merging isn't supported for a lot of tasks

For example, with the draw tool, I'd like to create a new atom at a set position or "create atom, bond, etc." in one merged undo.

I'm happy to do some of the coding, but it's a bit opaque what needs to change

**Comment by psavery** [comment]
I did try adding a 'm_molecule->undoStack().beginMacro("Adjust Hydrogens");' right after this line:

https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/editor/editor.cpp#L257

and 'm_molecule->undoStack().endMacro();' immediately after this line:

https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/editor/editor.cpp#L300

to see if I could lump in the adding of the hydrogen atoms together. Unfortunately, though, it just made it so I couldn't undo anything at all...

**Comment by cryos** [comment]
We never got to coalescing, this needs to be added, and we should add commands that combine the common operations like adding a molecule of a specific element at a specific location. The molecule is building up a QUndoStack, that can be manipulated.

I really want to put the work into having undo/redo commands rather than copies of the molecule like we did in v1. Open to suggestions, but it seems like it should be doable to group a number of operations.

**Comment by ghutchis** [comment]
I think the question is what new operations are needed. For example, it seems like there's a need for something like:

addFragment( vector< atoms >, vector< positions >, vector <bonds> )

etc. (e.g., there need to be some "batch" methods in RWMolecule)

**Comment by cryos** [comment]
I think undo stack has good grouping methods too, and would say that supporting the concept of all these belong together would also be nice (along with setting a name for that group that makes sense such as undo "adjust hydrogens", undo "move selected atoms".

**Comment by ghutchis** [comment]
I think this is fixed now, right @psavery ?

**Comment by psavery** [comment]
Yep! I just tried it out, and it looks good (I think). You can try it out too. Should be updated.
