### ISSUE TITLE
TLS initialization failure on 'Import From PQR' option

### ISSUE THREAD

**Issue by grsousajunior** [OpenChemistry/avogadrolibs#673]
**Avogadro version:**
 - Avogadrolibs: e.g. 1.94.0
 - Qt: 5.12.1

**Desktop version:**
 - OS: Microsoft Windows
 - Version: 10.0.19043.1083

**Describe the bug**
`Import From PQR` option is not working. Maybe related to #506.

**To Reproduce**
1. Go to `File > Import > Import From PQR`.
2. A dialog box shows up. Os `Search By` field type _benzene_.
3. Click on `Search` button.

**Screenshots**
![image](https://user-images.githubusercontent.com/56561421/125708385-7d21e0de-42c1-4c7e-b9aa-9f86958afb63.png)

**Comment by ghutchis** [comment]
If you go to https://pqr.pitt.edu/ yourself does it work?

**Comment by grsousajunior** [comment]
Yes. Works like a charm.

**Comment by ghutchis** [comment]
Okay, I'll look into this tomorrow.. Thanks for letting me know - at least there's a workaround since you can download from the website.

**Comment by ghutchis** [comment]
This turns out to be a common problem - we'll need to make sure we include OpenSSL libraries with the build:
https://stackoverflow.com/questions/53805704/tls-initialization-failed-on-get-request

It's a solvable problem, but might take a little while, since I don't have a Windows machine at home to check out the OpenSSL version, etc.
