### ISSUE TITLE
use scrollbar with file format list

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#706]
The "Export Molecule" functionality allows saving to a vast number of different file formats, 136 according to `obabel -L formats write`. 

Clicking on the file format list in the Export Molecule dialog, if you want to select a particular format then you have to tap down "manually" one by one until you reach the format you want.  It's quite laborious. It would be much easier if there was scrollbar that came with the list.

With other applications there's sometimes a scroll bar to roll through these lists, or so I thought.  Actually LibreOffice has the same problem. with no scrollbar to select alternative document file formats. Even gnumeric can't do it, with the list of spreadsheet file types.  Evidently it's a common problem, possibly system-dependent. Gimp does offers a scrollbar with "Export Image" file formats, though its format list seems to be organized in a different way.

I suspect Qt might have a way of activating a scrollbar with these listboxes. If that proves to be the case then it would be helpful to do it.

`QFileDialog` has `nameFilters()`, but not clear to me how the rendering of the filters in the dialog box is handled, and might not be the same thing. I can see avogadro has related code in FileFormatDialog::selectFileFormat(), qtgui/fileformatdialog.cpp, though not clear to me where scrollbar settings would go.

I'm using Gnome on Linux. Possibly it's a Gnome problem, might not be solvable by Qt or Avogadro.

**Comment by ghutchis** [comment]
Under the hood, we use `QFileDialog::getSaveFileName(…);` and just supply the list of name filters.

On Mac and Windows, these use the native save dialogs. While there's no scrollbar on my Mac, it's a popup menu / combobox and I can scroll like usual or type to skip to those items.

I tried some searching online, but I don't see anyone addressing this question - perhaps because most programs don't have as long a list.

I suspect this is a function of the Qt style - but if Gnumeric doesn't provide it, it may be a GNOME / GTK style issue.

I can say that the popup doesn't matter. If you type a particular extension, that should set the format that will be used.

**Comment by ghutchis** [comment]
While I understand this is frustrating, I think it should pick up format by extension by default. The menu is only a hint. So if you export and type "file.pdb" it should export a PDB file.

Otherwise, I'm open to suggestions, but it doesn't seem like an Avogadro-specific issue, more of a GTK / GNOME theme issue.
