### ISSUE TITLE
More selection commands

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#794]
A few simple ideas:
- [ ] Select backbone (protein / DNA)
- [ ] Select sidechain
- [x] Select small fragments (solvent molecules, salts, etc.)
- [x] Enlarge selection by X Å
- [x] Shrink selection by X Å (e.g., find the centroid, largest distance, then deselect anything too far)

Most of these could be done through modifying the current code.. not much needed

**Comment by Sid672** [comment]
@ghutchis please correct me if I am wrong. All changes can be done after modifying scale.py or another file also required changes. Link of the file given below:
https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/commandscripts/scripts/scale.py 
I am new to this project so can you provide me some docs so that I can understand more about the project and learn more about it.
