### ISSUE TITLE
Improve UX when there are multiple file readers

### ISSUE THREAD

**Issue by TiborGY** [OpenChemistry/avogadrolibs#932]
For some file extensions Avogadro currently asks the user which input reader would they like to use. Some of the input readers offered in these situations may not be suitable, and trying to read the file with them will result in an error message and the entire file open process is interrupted.

It would be a better UX to return the user to the format/reader selection dialog if loading the file fails, so the user can quickly choose another input reader, instead of having to browse to the path of the file they were trying to open, all over again.

See discussion at https://discuss.avogadro.cc/t/molpro-import-is-still-regressed-in-avogadro2-1-96-0-compared-to-avogadro1/3855

**Comment by ghutchis** [comment]
I think the precedence particularly for "out" or "log" files should be something like:
- If cclib is installed, try that
- Otherwise try Open Babel
- Otherwise try the internal code

**Comment by ghutchis** [comment]
Okay, this will now be handled by #1347 and #1348 together.

- One PR ensures that "out" and "log" formats are handled by code which determines the file type, then finds an appropriate reader.
- One PR auto-selects a format for the user unless shift / control / etc key is held down, in which case the dialog will appear.

I think this should resolve the issue, particularly if `cclib` is installed (since that has wide utility for Molpro and other compchem programs).
